# -*- coding: utf-8 -*-
"""mapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q7r1MQRCTGtnGGzVAM5ALxaS2wvgiqk6
"""

import numpy as np

def mapp(h):
  h=h.reshape((4,2))
  hnew=np.zeros((4,2),dtype=np.float32)

  add= h.sum(1)
  hnew[0]=h[np.argmin(add)]
  hnew[2]=h[np.argmax(add)]

  diff=np.diff(h,axis=1)
  hnew[1]=h[np.argmin(diff)]
  hnew[3]=h[np.argmax(diff)]

  return hnew